version: '3.8'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    networks:
      - app-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
  redis-data: