version: '3.8'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.stage.prod
    networks:
      - app-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  app-network:


volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
